- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: Copy mongodb repo # what is the copy module for ansible just type in google ansible copy module
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
  
  - name: Install mongodb  # similarly search ansible install package
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: allow remote conncections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'  # basically we check this in mongodb server by "netstat -lntp"
      replace: '0.0.0.0'

  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted